name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI
      
      - name: Install Playwright Package
        run: dotnet add package Microsoft.Playwright
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build Project
        run: dotnet build --configuration Release --no-restore
      
      - name: Install Playwright Browsers
        run: playwright install
      
      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Run Tests
        run: xvfb-run --auto-servernum dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results_${{ env.COMMIT_ID }}.trx"
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.COMMIT_ID }}
          path: test_results_${{ env.COMMIT_ID }}.trx